export const siteConfig = {
  name: "Capstone",
  title: "Capstone | Brand, Website, and Growth Systems for Modern Businesses",
  description:
    "Capstone helps ambitious businesses sharpen their brand, elevate their website, and build digital systems that support trust, conversion, and growth.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  bookingUrl:
    process.env.NEXT_PUBLIC_BOOKING_URL || "https://cal.eu/capstone/30min",
  email: "hello@capstone.com",
  phone: "+995 XXX XXX XXX",
  locations: ["Tbilisi", "London"],
  socials: [
    { label: "Instagram", href: "https://instagram.com/" },
    { label: "LinkedIn", href: "https://linkedin.com/" },
    { label: "Behance", href: "https://behance.net/" },
    { label: "GitHub", href: "https://github.com/" },
    { label: "X", href: "https://x.com/" },
    { label: "Discord", href: "https://discord.com/" },
  ],
  keywords: [
    "digital agency",
    "branding agency",
    "brand strategy",
    "website strategy",
    "web design",
    "web development",
    "website redesign",
    "enterprise web design",
    "enterprise digital agency",
    "mobile app development",
    "campaign creative",
    "conversion-focused website",
    "premium brand identity",
    "SEO content strategy",
    "creative agency",
    "brand identity",
    "digital growth",
  ],
};
